version: "3"

services:
  openra:
    image: openra
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/snd:/dev/snd"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
      - "/run/user/1000/pulse:/run/pulse:ro"
      - "./.openra:/home/game/.openra"
    networks:
      - main

networks:
  main:
